spring.application.name=springboot-restful-webservices-db

spring.datasource.url=jdbc:mysql://localhost:3306/usermanagement?useSSL=false
#dbc:mysql://localhost:3306/springjpadb?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=Jyo@6300

#hibernate
spring.jpa.properties.hiberate.dialect=orh.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
